// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Primary content in *Homepage → Slice zone → Introduction → Primary*
 */
export interface HomepageDocumentDataBodyIntroductionSlicePrimary {
	/**
	 * Name field in *Homepage → Slice zone → Introduction → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].introduction.primary.name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Short Description field in *Homepage → Slice zone → Introduction → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 3 word short description to be used beside the title
	 * - **API ID Path**: homepage.body[].introduction.primary.short_description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	short_description: prismic.KeyTextField;
	
	/**
	 * Description field in *Homepage → Slice zone → Introduction → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].introduction.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * Current Website URL field in *Homepage → Slice zone → Introduction → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Current URL of the website
	 * - **API ID Path**: homepage.body[].introduction.primary.current_website_url
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	current_website_url: prismic.KeyTextField;
	
	/**
	 * LinkedIn URL field in *Homepage → Slice zone → Introduction → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].introduction.primary.linkedin_url
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	linkedin_url: prismic.LinkField;
	
	/**
	 * Instagram URL field in *Homepage → Slice zone → Introduction → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].introduction.primary.instagram_url
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	instagram_url: prismic.LinkField;
	
	/**
	 * GitHub URL field in *Homepage → Slice zone → Introduction → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].introduction.primary.github_url
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	github_url: prismic.LinkField;
	
	/**
	 * E-mail Address field in *Homepage → Slice zone → Introduction → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].introduction.primary.public_email
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	public_email: prismic.KeyTextField;
	
	/**
	 * Resume field in *Homepage → Slice zone → Introduction → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].introduction.primary.resume
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	resume: prismic.LinkToMediaField;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyIntroductionSlice = prismic.Slice<"introduction", Simplify<HomepageDocumentDataBodyIntroductionSlicePrimary>, never>

/**
 * Item content in *Homepage → Slice zone → Technologies → Items*
 */
export interface HomepageDocumentDataBodyTechnologiesSliceItem {
	/**
	 * Logo field in *Homepage → Slice zone → Technologies → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].technologies.items.logo
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;
	
	/**
	 * Name field in *Homepage → Slice zone → Technologies → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].technologies.items.name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyTechnologiesSlice = prismic.Slice<"technologies", Record<string, never>, Simplify<HomepageDocumentDataBodyTechnologiesSliceItem>>

/**
 * Item content in *Homepage → Slice zone → Job Background → Items*
 */
export interface HomepageDocumentDataBodyJobBackgroundSliceItem {
	/**
	 * Position field in *Homepage → Slice zone → Job Background → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].job_background.items.position
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	position: prismic.KeyTextField;
	
	/**
	 * Company field in *Homepage → Slice zone → Job Background → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].job_background.items.company
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	company: prismic.KeyTextField;
	
	/**
	 * Start Year field in *Homepage → Slice zone → Job Background → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].job_background.items.start_year
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	start_year: prismic.KeyTextField;
	
	/**
	 * End Year field in *Homepage → Slice zone → Job Background → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].job_background.items.end_year
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	end_year: prismic.KeyTextField;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyJobBackgroundSlice = prismic.Slice<"job_background", Record<string, never>, Simplify<HomepageDocumentDataBodyJobBackgroundSliceItem>>

/**
 * Item content in *Homepage → Slice zone → Educational Background → Items*
 */
export interface HomepageDocumentDataBodyEducationalBackgroundSliceItem {
	/**
	 * Course field in *Homepage → Slice zone → Educational Background → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].educational_background.items.course
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	course: prismic.KeyTextField;
	
	/**
	 * School field in *Homepage → Slice zone → Educational Background → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].educational_background.items.school
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	school: prismic.KeyTextField;
	
	/**
	 * Start Year field in *Homepage → Slice zone → Educational Background → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].educational_background.items.start_year
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	start_year: prismic.KeyTextField;
	
	/**
	 * End Year field in *Homepage → Slice zone → Educational Background → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].educational_background.items.end_year
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	end_year: prismic.KeyTextField;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyEducationalBackgroundSlice = prismic.Slice<"educational_background", Record<string, never>, Simplify<HomepageDocumentDataBodyEducationalBackgroundSliceItem>>

type HomepageDocumentDataBodySlice = HomepageDocumentDataBodyIntroductionSlice | HomepageDocumentDataBodyTechnologiesSlice | HomepageDocumentDataBodyJobBackgroundSlice | HomepageDocumentDataBodyEducationalBackgroundSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Slice zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	body: prismic.SliceZone<HomepageDocumentDataBodySlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

/**
 * Content for Project Tag documents
 */
interface ProjectTagDocumentData {
	/**
	 * Name field in *Project Tag*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_tag.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Border / Text Color field in *Project Tag*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_tag.border_color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	border_color: prismic.ColorField;
	
	/**
	 * Background Color field in *Project Tag*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_tag.background_color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	background_color: prismic.ColorField;
}

/**
 * Project Tag document from Prismic
 *
 * - **API ID**: `project_tag`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectTagDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<ProjectTagDocumentData>, "project_tag", Lang>;

/**
 * Item in *Projects → Tags*
 */
export interface ProjectsDocumentDataTagsItem {
	/**
	 * Tag field in *Projects → Tags*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.tags[].tag
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	tag: prismic.ContentRelationshipField<"project_tag">;
}

/**
 * Item in *Projects → Images*
 */
export interface ProjectsDocumentDataImagesItem {
	/**
	 * Image field in *Projects → Images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.images[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Caption field in *Projects → Images*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.images[].caption
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	caption: prismic.KeyTextField;
}

/**
 * Content for Projects documents
 */
interface ProjectsDocumentData {
	/**
	 * Project Name / Title field in *Projects*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	name: prismic.TitleField;
	
	/**
	 * Type field in *Projects*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Case Study
	 * - **API ID Path**: projects.type
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	type: prismic.SelectField<"Case Study" | "Project", "filled">;
	
	/**
	 * Tags field in *Projects*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.tags[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	tags: prismic.GroupField<Simplify<ProjectsDocumentDataTagsItem>>;
	
	/**
	 * Images field in *Projects*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.images[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	images: prismic.GroupField<Simplify<ProjectsDocumentDataImagesItem>>;
	
	/**
	 * Project Link field in *Projects*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.project_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	project_link: prismic.LinkField;
	
	/**
	 * Website Link field in *Projects*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.website_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	website_link: prismic.LinkField;
	
	/**
	 * Short Description field in *Projects*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.short_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	short_description: prismic.RichTextField;
	
	/**
	 * Description field in *Projects*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<ProjectsDocumentData>, "projects", Lang>;

export type AllDocumentTypes = HomepageDocument | ProjectTagDocument | ProjectsDocument;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataBodyIntroductionSlicePrimary,
			HomepageDocumentDataBodyTechnologiesSliceItem,
			HomepageDocumentDataBodyJobBackgroundSliceItem,
			HomepageDocumentDataBodyEducationalBackgroundSliceItem,
			HomepageDocumentDataBodySlice,
			ProjectTagDocument,
			ProjectTagDocumentData,
			ProjectsDocument,
			ProjectsDocumentData,
			ProjectsDocumentDataTagsItem,
			ProjectsDocumentDataImagesItem,
			AllDocumentTypes
		}
	}
}